### ISSUE TITLE
[💻 Hack Pod] Hack on Documentation with Blacktocats 12/15?

### ISSUE THREAD

**Issue by manishapriya94** [ProgramEquity/open-source-mentorship#11]
<img width="684" alt="Screen Shot 2023-02-06 at 6 52 48 AM" src="https://user-images.githubusercontent.com/9143339/217004604-d59ea33e-1318-47fa-a6d9-dbdfe415e62d.png">

# When
Wednesday, February 15th, 11:30 -1 pm pt 
https://github.zoom.us/j/97013759503?pwd=aDd5NmNKQTNsbGlLQWhuSm4vVEFGdz09
Event Details: 40-80$ of Benevity donations 

## What are we hacking on? 
**Goal:** Improve Amplify's documentation and use it to provide a good model of documentation and OSS maintainership for MLH fellows

## Background
As part of our ongoing Open Source Mentorship program, fellows have been working on [Amplify](https://github.com/programequity/amplify).  We'd like to clean up and organize the documentation, add some things to improve the contributor workflow, and start working on documenting the app's API endpoints and third party API usage using OpenAPI

### Project Documentation
- [ ] https://github.com/ProgramEquity/amplify/issues/357
- [ ] https://github.com/ProgramEquity/amplify/issues/356

#### Issues
- [ ] https://github.com/ProgramEquity/amplify/issues/125
- [ ] https://github.com/ProgramEquity/amplify/issues/411
- [ ] https://github.com/ProgramEquity/amplify/issues/492

#### Draft PRs

- [ ] https://github.com/ProgramEquity/amplify/pull/272
- [ ] https://github.com/ProgramEquity/amplify/pull/412

### Contributor Workflow Improvements

- [ ] https://github.com/ProgramEquity/amplify/issues/355
- [ ] https://github.com/ProgramEquity/amplify/issues/410
- [ ] https://github.com/ProgramEquity/amplify/issues/413

### Resources: 
- [Workshop Recording on Documentation](https://programequity.notion.site/OSS-Workshop-Documenting-your-project-9d57308f0a2d41e9a8c4c2bfbe568ef3) 
- [OSS Documentation Example Repo](https://github.com/therzka/OSS-Example-Repo/blob/main/README.md)

**Comment by blackgirlbytes** [comment]
I volunteer

**Comment by blackgirlbytes** [comment]
@ghostinhershell is also interested!

**Comment by manishapriya94** [comment]
@ipc103 do you think folks from ospo would join this event in celebration with Octo7 and Blacktocats?

**Comment by ipc103** [comment]
Good idea - I shared this with our team ❤️ I have a conflict but will try to join for at least part of the time.
