### ISSUE TITLE
[Workshop] Test Driven Development feat. Stripe |  February 23rd, 2023

### ISSUE THREAD

**Issue by therzka** [ProgramEquity/open-source-mentorship#12]
### Speaker info

Name: Charlie Gerard, Cecil Phillips
Bio:
LinkedIn: 
https://www.linkedin.com/in/cecil-phillip
https://www.linkedin.com/in/charliegerard

### Workshop Links
Zoom Link: https://github.zoom.us/j/97013759503?pwd=aDd5NmNKQTNsbGlLQWhuSm4vVEFGdz09
Eventbrite link: https://www.eventbrite.com/e/test-driven-development-with-stripe-tickets-531656808827?aff=ebdsoporgprofile
Notion Card Link: https://www.notion.so/programequity/Test-Driven-Development-With-Stripe-40de27d593d748e08fdf47296807eab5

### Presentation Materials

- Link to slides:  https://docs.google.com/presentation/d/18-3D7pBsun3lrrpeX_1ZZJFYoAmAXTyTG6vDWbb6RUc/edit#slide=id.ga3fa2ad6e1_0_0

**Comment by manishapriya94** [comment]
Recapping our notes @charliegerard-stripe cc: @cecilphillip-stripe, feel free to drop slides link in comments

- Fellows attended #10 last week
- Great examples for test driven dev, we are mostly using checkout if that helps to focus the preso
- Here are examples of bugs we'll have them hack 
- As well as integration tests that could be good to build (we'll defer to you here)
- Thankful that we're exploring all of these capabilities without the dashboard! 

We've had other speakers do a bit of a LinkedIn/Twitter challenge so fellows can post what they're learning in real time - any hashtags or prompts we should be aware of? Ex: 
<img width="431" alt="Screen Shot 2023-02-22 at 6 20 09 AM" src="https://user-images.githubusercontent.com/9143339/220648729-a59cbb64-a054-43c2-960a-7df810e61c12.png">

**Comment by charliegerard-stripe** [comment]
Hey @manishapriya94, I realized as Cecil and I put the deck together using Google Slides, it can only be shared internally within Stripe :/ I'll try and find a way to share it after the workshop but I probably won't have time before, sorry about that!

**Comment by therzka** [comment]
@charliegerard-stripe no worries, getting it to us after the workshop is fine :)

Was about to email you to let you know I'll be in the chat today to field questions and drop links if necessary, let me know if you need anything!

**Comment by charliegerard-stripe** [comment]
@therzka Here's the link to the slides! 😃 https://docs.google.com/presentation/d/18-3D7pBsun3lrrpeX_1ZZJFYoAmAXTyTG6vDWbb6RUc/edit?usp=sharing

**Comment by therzka** [comment]
@charliegerard-stripe thank you so much and thank you for the wonderful presentation!
